loadTimeData.data = {
  bestScore: "最佳 $1 $2 $3",
  bestScoreFlyout: "最高分：$1",
  bestScoreMenuDisplay: "$1 $2",
  cancel: "取消",
  close: "关闭",
  code: "作弊码已激活！",
  codeCheat: "作弊码已激活！ $1",
  codeScoring: "本次回合已关闭计分。",
  endlessBestScore: -1,
  endlessDescriptor: "距离",
  endlessModeTitleInline: "无限模式：",
  endlessTitle: "无限模式",
  endlessUnit: "米",
  fontfamily: "system-ui, sans-serif",
  fontsize: "75%",
  gameCreditsButton: "游戏制作人员",
  gameCreditsDialogTitle: "游戏制作人员",
  gameMode: "游戏模式已更改为 $1",
  gameModeSelectLabel: "游戏模式",
  gameModeSelectLabelDisabled: "游戏模式（需开始新游戏才能更改）",
  gameSettings: "游戏设置",
  highVisibilityActive: false,
  highVisiblityModeToggleLabel: "高对比度",
  howToPlayButton: "玩法说明",
  howToPlayControllerBoost: "按 RT 键使用加速",
  howToPlayControllerMovement: "使用摇杆或方向键转向",
  howToPlayControllerRefresh: "按下 LB+RB 重新开始游戏",
  howToPlayDialogTitle: "玩法说明",
  howToPlayEndless:
    "尽可能滑得更远，并救下朋友来帮你对付敌人",
  howToPlayKeyboardBoost: "按 `F` 键使用加速",
  howToPlayKeyboardMovement: "使用方向键或 `WASD` 键转向",
  howToPlayKeyboardRefresh: "刷新页面以重新开始游戏",
  howToPlayMouseBoost: "单击鼠标右键使用加速",
  howToPlayMouseMovement: "移动鼠标来转向",
  howToPlayMouseRefresh: "刷新页面以重新开始游戏",
  howToPlayTimeTrial:
    "尽快到达终点，并收集硬币以减少你的用时",
  howToPlayTouchBoost: "向下滑动两次以使用加速",
  howToPlayTouchMovement: "滑动或点击以转向",
  howToPlayTouchRefresh: "刷新页面以重新开始游戏",
  howToPlayZigZag: "尽可能连续穿过最多的门",
  is_windows_xbox_sku: "false",
  keyboardAction: "空格键",
  language: "zh", 
      // 已将 "en" 更改为 "zh" 代表中文
  lastSelectedMode: "endless",
  lastSelectedPlayer: 4,
  lastSelectedTheme: "surf",
  menuInfo: "开始游戏",
  mouseAction: "双击",
  newBestScore: "新的最高 $1 $2 $3！",
  newGame: "开始新游戏",
  off: "关闭",
  on: "开启",
  overInfo: "再玩一次",
  overTitle: "干得不错！",
  pauseInfo: "继续游戏",
  pauseTitle: "游戏已暂停",
  reducedSpeedActive: false,
  reducedSpeedModeToggleLabel: "减速模式",
  resetAllStats: "重置所有数据",
  resetAllStatsDialogText:
    "你确定要重置所有游戏数据吗？包括你的最高分。",
  resetAllStatsDialogTitle: "重置所有数据",
  share: "与朋友分享",
  shareCopy: "复制",
  shareLink: "https://surf.guangzhoueven.dpdns.org/",
  shareLinkCopied: "已复制！",
  skiTheme: "去滑雪",
  specialThanks: "特别鸣谢：",
  surfTheme: "去冲浪",
  textdirection: "ltr", 
     // 对大多数情况，中文布局也是从左到右
  theme: "主题已更改为 $1",
  themeSelectLabel: "主题",
  timetrialBestScore: -1,
  timetrialDescriptor: "时间",
  timetrialModeTitleInline: "计时赛：",
  timetrialTitle: "计时赛",
  timetrialUnit: "秒",
  touchAction: "双击",
  zigzagBestScore: -1,
  zigzagDescriptor: "连续穿过",
  zigzagModeTitleInline: "Z字形冲浪：",
  zigzagTitle: "Z字形冲浪",
  zigzagUnit: "门",
};